# Generated by Django 4.2.6 on 2023-10-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('romanized_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['romanized_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('romanized_name', models.CharField(max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomy.unit')),
                ('voice_actor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='person.artist')),
            ],
            options={
                'ordering': ['romanized_name', 'name'],
            },
        ),
    ]
