# Generated by Django 4.2.6 on 2023-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='aliases',
            field=models.ManyToManyField(blank=True, to='person.artist'),
        ),
    ]
