# Generated by Django 4.2.6 on 2023-10-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_artist_slug_character_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='character',
            name='slug',
        ),
    ]
