# Generated by Django 4.2.6 on 2023-10-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('person', '0003_artist_slug_character_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('romanized_title', models.CharField(blank=True, max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxonomy.area')),
                ('arranger', models.ManyToManyField(blank=True, related_name='arranged_songs', to='person.artist')),
                ('composer', models.ManyToManyField(blank=True, related_name='composed_songs', to='person.artist')),
                ('lyricist', models.ManyToManyField(blank=True, related_name='written_songs', to='person.artist')),
                ('singer', models.ManyToManyField(blank=True, related_name='sung_songs', to='person.character')),
            ],
            options={
                'ordering': ['-area__identifier', 'romanized_title', 'title'],
            },
        ),
    ]
