# Generated by Django 4.2.6 on 2023-10-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0002_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Release',
        ),
    ]
