# Generated by Django 4.2.6 on 2023-10-17 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0003_rename_album_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('SL', 'Single'), ('CD', 'Album')], default='SL', max_length=2),
        ),
    ]
