# Generated by Django 4.2.6 on 2023-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0004_release_release_date_release_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('SL', 'Single'), ('EP', 'EP'), ('CD', 'Album')], default='SL', max_length=2),
        ),
    ]
