# Generated by Django 4.2.6 on 2023-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0006_song_genre_song_jacket_image_song_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='jacket_image',
        ),
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
