# Generated by Django 4.2.6 on 2023-10-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('creations', '0008_alter_song_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.area'),
        ),
    ]
