# Generated by Django 4.2.6 on 2023-10-17 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0009_alter_song_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
