# Generated by Django 4.2.6 on 2023-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('creations', '0010_alter_song_bpm_alter_song_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-areas__identifier', 'romanized_title', 'title']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='area',
        ),
        migrations.AddField(
            model_name='song',
            name='areas',
            field=models.ManyToManyField(blank=True, to='taxonomy.area'),
        ),
    ]
