# Generated by Django 4.2.6 on 2023-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_artist_slug_character_slug'),
        ('creations', '0011_alter_song_options_remove_song_area_song_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['romanized_title', 'title']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='areas',
        ),
        migrations.AddField(
            model_name='song',
            name='remixer',
            field=models.ManyToManyField(blank=True, related_name='remixed_songs', to='person.character'),
        ),
    ]
