# Generated by Django 4.2.6 on 2023-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0013_alter_song_remixer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('songs', models.ManyToManyField(related_name='releases', to='creations.release')),
            ],
        ),
    ]
