# Generated by Django 4.2.6 on 2023-10-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0014_releasecampaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasecampaign',
            old_name='songs',
            new_name='releases',
        ),
    ]
