# Generated by Django 4.2.6 on 2023-10-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0015_rename_songs_releasecampaign_releases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['release_type', 'romanized_title', 'title']},
        ),
    ]
