# Generated by Django 4.2.6 on 2023-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0016_alter_release_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='english_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
