# Generated by Django 4.2.6 on 2023-10-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0017_song_english_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creations.song'),
        ),
    ]
